export const GESTURE = {
    HANDS_FOLDING: 'HANDS_FOLDING',
    HANDS_UNFOLDING: 'HANDS_UNFOLDING',
    WAVE_IN: 'WAVE_IN',
    WAVE_OUT: 'WAVE_OUT',
    FIST_AND_THROW_AWAY: 'FIST_AND_THROW_AWAY',
    HANDS_UPWARD: 'HANDS_UPWARD',
    INDEX_FINGER_LEFT: 'INDEX_FINGER_LEFT',
    INDEX_FINGER_RIGHT: 'INDEX_FINGER_RIGHT',
    STOP: 'STOP',
    SWIPE_LEFT: 'SWIPE_LEFT'
}

export const CONTEXT = {
    DEFAULT: 'DEFAULT',
    SELECTED: 'SELECTED',
    REPLACE: 'REPLACE',
    INSERT_BEFORE: 'INSERT_BEFORE',
    INSERT_AFTER: 'INSERT_AFTER',
    SELECTING: 'SELECTING'
}

export const MODALITY = {
    VOICE: 'VOICE',
    GESTURE: 'GESTURE'
}
